## Katrina Johnson - DSB Unit 2.5.2

## Challenge: Make Your Own Regression Model

Now that you've spent some time playing with a sample multivariate linear regression model, it's time to make your own.

You've already gotten started by prepping the FBI:UCR Crime dataset (Thinkful mirror) in a previous assignment.

Using this data, build a regression model to predict property crimes. You can use the features you prepared in the previous assignment, new features of your own choosing, or a combination. The goal here is prediction rather than understanding mechanisms, so the focus is on creating a model that explains a lot of variance.

Submit a notebook with your model and a brief writeup of your feature engineering and selection process to submit and review with your mentor.

## My Steps for Completing DSB Unit 2.5.2 Challenge

1. Download two datasets.  
2. Run the predicitve model I created in challenge 2.3.3 on both data sets.   
3. Evaluate the results to find out how consistently the predictive model works.
4. Use error calculating mechanism I created to test the sentiment or span in the naive bayes' lessons to text for accuracy.
5. Use the methods I learned in DSB Unit 5.1 to calculate the CI, R^2, pvalue, and Intercept and coefficients.
6. Analyze the results of the calculations made in step 5, and write about them, and write about how to address any apparent problems that I notice.

training a model means using sklearn's fit() method.  
I will need X and a Y variables
X is every feature that I want to go into the model that is not the outcome feature.  For example, if I am predicting property crime, I kick property crime out of X and make property crime Y.

Then instantiate my linear regression model.  Next, I do the fit(X, Y).  This creates a linear regression model.
Afterwards, I can call the following methods on the model: score(X,Y) or a predict(X) 

If I use Y_pred = NameIGiveTheRegressionModel.predict(X)
Now, I can compare Y_pred to Y.  This will tell me the residual of the model against each data point.  (i.e. the residual is the distance between each data point and the line. There is one residual for each data point.  This is why I can plot the residual on the Y axis and also on the X axis.)

To eveluate how good a model is at dealing with new data, do not refit the model.  Why?  Because if you do, it will be a different model.

Take my Oregon crime statistic data, make sure it has the same number of features, and in the same order as the New York crime statistic data.  This is because the model ignores column titles.  It only looks at the order in which they appear in the data set.

For Oregon_df
X1 = all features I choose to use, except Property Crime.
Y1 = Property crime.

For df  ..which is the NY data - I have aleady done this:
X = all features I choose to use, except Property Crime.  Y = Property crime. (I could call these X_train...and Y_train)

Once I do everything to X1 and Y1 that I did to the NewYork X and Y, and run (i.e. plug them into) the same model as the variable that will be fit, ...Then I can compare them using score(X,Y) and predict (Y) and score(X1, Y1) and predict(X1).

In [35]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
from sklearn import linear_model
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [2]:
#plt.style.use('dark_background')

In [3]:
df = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls')
#df

In [4]:
Oregon_df = pd.read_excel('table_8_offenses_known_to_law_enforcement_oregon_by_city_2013.xls')
#Oregon_df

In [5]:
df.columns = ['City', 'Population', 'Violent crime', 'Murder and nonnegligent manslaughter', 
              'Rape (revised definition) 1', 'Rape (legacy definition) 2', 'Robbery', 'Aggravated assault', 
              'Property crime', 'Burglary', 'Larceny theft', 'Motor vehicle theft', 'Arson 3']

#df

In [6]:
Oregon_df.columns = ['City', 'Population', 'Violent crime', 'Murder and nonnegligent manslaughter', 
                     'Rape (revised definition) 1','Rape (legacy definition) 2', 'Robbery', 'Aggravated assault',
                     'Property crime', 'Burglary', 'Larceny theft', 'Motor vehicle theft', 'Arson']
#Oregon_df

In [7]:
df = df.drop(0)
df = df.drop(1)
df = df.drop(2)
df = df.drop(3)
df = df.drop(columns = ['City', 'Rape (revised definition) 1', 'Rape (legacy definition) 2', 'Arson 3'])
#df = df.drop(['Rape (revised definition) 1'], axis=1)
#df = df.drop(['Rape (legacy definition) 2'], axis=1)
#df = df.drop(['Arson 3'], axis=1)
df = df.drop(352)
df = df.drop(353)
df = df.drop(354)
#df

In [8]:
Oregon_df = Oregon_df.drop(0)
Oregon_df = Oregon_df.drop(1)
Oregon_df = Oregon_df.drop(2)
Oregon_df = Oregon_df.drop(3)
Oregon_df = Oregon_df.drop(columns = ['City'], axis=0)
Oregon_df = Oregon_df.drop(['Rape (revised definition) 1'], axis=1)
Oregon_df = Oregon_df.drop(['Rape (legacy definition) 2'], axis=1)
Oregon_df = Oregon_df.drop(['Arson'], axis=1)
Oregon_df = Oregon_df.drop(113)
Oregon_df = Oregon_df.drop(114)
Oregon_df = Oregon_df.dropna(how='all')
Oregon_df

,Population,Violent crime,Murder and nonnegligent manslaughter,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft
4,51645,40,0,27,5,2019,252,1625,142
5,1624,1,0,0,0,26,1,25,0
6,20455,33,0,7,21,674,76,585,13
7,9543,33,0,1,29,445,89,324,32
8,1144,1,0,0,0,25,5,19,1
9,3738,6,0,1,5,82,20,59,3
10,9660,27,0,2,24,370,68,293,9
11,3039,1,0,1,0,88,24,59,5
12,1862,4,0,0,4,26,5,17,4
13,93551,124,1,22,81,1471,175,1213,83
14,79926,182,1,22,138,2267,267,1913,87
15,NaN,0,0,0,0,5,0,5,0
16,3369,8,0,0,5,84,22,58,4
17,6313,2,0,1,1,55,6,43,6
18,2706,1,0,0,1,66,19,43,4
19,16031,13,0,2,7,298,60,229,9
20,1692,1,0,0,1,38,1,35,2
21,2022,4,0,0,1,18,3,15,0
22,17485,33,0,4,24,601,47,530,24
23,1726,0,0,0,0,51,19,28,4
24,1043,0,0,0,0,15,5,9,1
25,1938,0,0,0,0,11,0,10,1
26,722,0,0,0,0,2,0,2,0
27,15816,60,1,6,50,965,166,745,54
28,3826,0,0,0,0,67,12,51,4
29,12231,18,0,9,5,351,66,271,14
30,55218,64,0,16,38,1587,195,1354,38
31,9795,18,1,5,12,509,52,436,21
32,14803,41,0,4,31,315,51,254,10
33,8669,24,0,8,12,344,43,294,7
...,...,...,...,...,...,...,...,...,...
83,9161,24,0,1,22,295,45,249,1
84,1887,2,0,1,1,43,6,33,4
85,27153,87,0,15,61,1067,157,867,43
86,1313,2,0,0,2,48,20,28,0
87,2173,2,0,0,2,45,7,33,5
88,158234,520,7,138,328,6782,983,5143,656
89,6677,11,0,1,10,82,14,66,2
90,6475,8,0,4,2,554,74,465,15
91,18932,8,0,2,4,301,31,260,10
92,9380,10,1,3,4,207,28,173,6
93,60024,98,2,32,50,3198,478,2450,270
94,2058,2,0,0,1,29,6,19,4
95,7733,23,0,5,15,337,46,278,13
96,12917,9,0,2,2,353,46,291,16
97,NaN,2,0,0,2,80,16,60,4
98,9035,10,0,4,5,501,82,398,21
99,6191,7,0,0,5,131,12,115,4
100,13831,14,0,6,7,692,141,513,38
101,50311,57,0,23,20,1626,173,1384,69
102,4932,10,0,4,5,177,23,142,12
103,3461,16,1,2,11,145,37,103,5
104,16566,22,0,9,10,509,64,396,49
105,26925,24,0,9,8,783,88,658,37
106,1896,1,1,0,0,24,7,15,2
107,7040,13,0,0,11,107,25,70,12
108,5146,0,0,0,0,167,25,134,8
109,25744,6,0,0,3,279,36,234,9
110,20819,17,0,6,5,461,51,374,36
111,24263,82,1,28,46,733,100,586,47
112,1040,0,0,0,0,16,3,13,0

In [9]:
df.isna().sum()

Population                              0
Violent crime                           0
Murder and nonnegligent manslaughter    0
Robbery                                 0
Aggravated assault                      0
Property crime                          0
Burglary                                0
Larceny theft                           0
Motor vehicle theft                     0
dtype: int64

In [10]:
Oregon_df.isna().sum()

Population                              2
Violent crime                           0
Murder and nonnegligent manslaughter    0
Robbery                                 0
Aggravated assault                      0
Property crime                          0
Burglary                                0
Larceny theft                           0
Motor vehicle theft                     0
dtype: int64

In [11]:
Oregon_df['Population']

4       51645
5        1624
6       20455
7        9543
8        1144
9        3738
10       9660
11       3039
12       1862
13      93551
14      79926
15        NaN
16       3369
17       6313
18       2706
19      16031
20       1692
21       2022
22      17485
23       1726
24       1043
25       1938
26        722
27      15816
28       3826
29      12231
30      55218
31       9795
32      14803
33       8669
        ...
83       9161
84       1887
85      27153
86       1313
87       2173
88     158234
89       6677
90       6475
91      18932
92       9380
93      60024
94       2058
95       7733
96      12917
97        NaN
98       9035
99       6191
100     13831
101     50311
102      4932
103      3461
104     16566
105     26925
106      1896
107      7040
108      5146
109     25744
110     20819
111     24263
112      1040
Name: Population, Length: 109, dtype: object

In [12]:

Oregon_df = Oregon_df.dropna()
#Oregon_df = Oregon_df.dropna(Oregon_df.index[97])
Oregon_df['Population']

4       51645
5        1624
6       20455
7        9543
8        1144
9        3738
10       9660
11       3039
12       1862
13      93551
14      79926
16       3369
17       6313
18       2706
19      16031
20       1692
21       2022
22      17485
23       1726
24       1043
25       1938
26        722
27      15816
28       3826
29      12231
30      55218
31       9795
32      14803
33       8669
34       1870
        ...
82     609136
83       9161
84       1887
85      27153
86       1313
87       2173
88     158234
89       6677
90       6475
91      18932
92       9380
93      60024
94       2058
95       7733
96      12917
98       9035
99       6191
100     13831
101     50311
102      4932
103      3461
104     16566
105     26925
106      1896
107      7040
108      5146
109     25744
110     20819
111     24263
112      1040
Name: Population, Length: 107, dtype: object

In [13]:
Oregon_df.isna().sum()

Population                              0
Violent crime                           0
Murder and nonnegligent manslaughter    0
Robbery                                 0
Aggravated assault                      0
Property crime                          0
Burglary                                0
Larceny theft                           0
Motor vehicle theft                     0
dtype: int64

Oregon_corr = Oregon_df.corr()
sns.heatmap(Oregon_corr, xticklabels=Oregon_corr.columns.values,
           yticklabels=corr.columns.values)

#Example: df.drop(columns=['B', 'C'])

corr = df.corr()
sns.heatmap(corr, xticklabels=corr.columns.values, 
            yticklabels=corr.columns.values)

## Divide the features by the population.  Mark suggested this.  As I mentioned in my ticket on Slack, I have already tried it. (Here, once again, it yields zeros.)

df['Violent crime'] = df['Violent crime'] / df['Population']
df['Murder and non negligent manslaughter'] = df['Murder and nonnegligent manslaughter'] / df['Population']
df['Robbery'] = df['Robbery'] / df['Population']
df['Aggravated assault'] = df['Aggravated assault'] / df['Population']
df['Property crime'] = df['Property crime'] / df['Population']
df['Burglary'] = df['Burglary'] / df['Population']
df['Larceny theft'] = df['Larceny theft'] / df['Population']
df['Motor vehicle theft'] = df['Motor vehicle theft'] / df['Population']
df

In [22]:
## Instantiate and fit the training model.
regr_train = linear_model.LinearRegression()
Y_train = df['Property crime']
X_train = df[['Murder and nonnegligent manslaughter', 'Robbery', 'Aggravated assault', 'Burglary',
           'Larceny theft', 'Motor vehicle theft']]
regr_train.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [30]:
## Instantiate and fit the test model.
regr = linear_model.LinearRegression()
Y1 = Oregon_df['Property crime']
X1 = Oregon_df[['Murder and nonnegligent manslaughter', 'Robbery', 'Aggravated assault', 'Burglary',
           'Larceny theft', 'Motor vehicle theft']]
regr.fit(X1, Y1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [29]:
# Inspect the results
print('\nTraining Model Inspection Results:')
print('\nCoefficients: \n', regr_train.coef_)
print('\nIntercept: \n', regr_train.intercept_)
print('\nR-squared:', regr_train.score(X_train, Y_train))

Training Model Inspection Results:

Coefficients:
 [-3.47381681e-13  4.88498131e-15 -9.43689571e-16  1.00000000e+00
  1.00000000e+00  1.00000000e+00]

Intercept:
 3.410605131648481e-13

R-squared: 1.0

In [34]:
# Inspect the results
print('\nTraining Model Inspection Results:')
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:', regr.score(X_train, Y_train))

Training Model Inspection Results:

Coefficients:
 [-1.42656166e-12 -4.44089210e-16  1.27675648e-15  1.00000000e+00
  1.00000000e+00  1.00000000e+00]

Intercept:
 -5.684341886080801e-13

R-squared: 1.0

In [38]:
Y_train_pred = regr_train.predict(X_train)
Y_train_pred

array([1.20000000e+01, 2.40000000e+01, 1.60000000e+01, 4.09000000e+03,
       2.23000000e+02, 4.60000000e+01, 1.00000000e+01, 2.11800000e+03,
       2.10000000e+02, 4.05000000e+02, 3.90000000e+01, 3.30000000e+01,
       2.00000000e+00, 5.00000000e+00, 8.59000000e+02, 2.50000000e+01,
       8.80000000e+01, 9.40000000e+01, 5.59000000e+02, 1.91000000e+02,
       1.56000000e+02, 4.42000000e+02, 2.34900000e+03, 1.40000000e+01,
       9.90000000e+01, 4.00000000e+00, 2.40000000e+01, 2.00000000e+01,
       3.10000000e+01, 1.30000000e+01, 1.10000000e+01, 7.93000000e+02,
       1.65000000e+02, 4.70000000e+01, 1.00000000e+01, 1.24910000e+04,
       1.50000000e+01, 4.40000000e+01, 4.60000000e+01, 3.48000000e+02,
       3.15000000e+02, 6.00000000e+01, 1.20000000e+01, 9.30000000e+01,
       2.00000000e+00, 1.98000000e+02, 8.00000000e+00, 6.00000000e+01,
       4.00000000e+00, 5.90000000e+01, 5.80000000e+01, 5.30000000e+01,
       3.20000000e+01, 2.68900000e+03, 2.50000000e+01, 6.50000000e+01,
       4.40000000e+02, 1.51500000e+03, 6.00000000e+01, 2.18000000e+02,
       8.60000000e+01, 2.43000000e+02, 1.99000000e+03, 1.60000000e+01,
       4.16000000e+02, 2.20000000e+01, 4.20000000e+01, 3.98000000e+02,
       1.13000000e+02, 5.30000000e+01, 8.10000000e+01, 1.52000000e+02,
       1.52000000e+02, 3.60000000e+01, 3.10000000e+02, 1.40000000e+01,
       7.15000000e+02, 8.00000000e+00, 1.04000000e+02, 4.10000000e+01,
       9.90000000e+01, 3.07000000e+02, 1.31000000e+02, 1.68000000e+02,
       1.65000000e+02, 3.73000000e+02, 3.00000000e+02, 6.60000000e+01,
       1.25000000e+02, 1.47000000e+02, 3.10000000e+01, 1.73000000e+02,
       2.88000000e+02, 1.02700000e+03, 8.90000000e+01, 1.00000000e+00,
       6.04000000e+02, 3.13000000e+02, 5.30000000e+01, 1.62000000e+02,
       2.76000000e+02, 7.20000000e+01, 4.40000000e+01, 9.00000000e+01,
       5.00000000e+01, 3.30000000e+01, 3.20000000e+01, 2.08000000e+02,
       9.33000000e+02, 1.60000000e+01, 4.63000000e+02, 3.46000000e+02,
       1.05100000e+03, 2.51000000e+02, 1.62000000e+02, 3.43000000e+02,
       9.00000000e+00, 6.20000000e+01, 5.00000000e+00, 3.43000000e+02,
       4.92000000e+02, 6.86000000e+02, 6.40000000e+01, 2.90000000e+01,
       2.60000000e+01, 2.00000000e+01, 2.30300000e+03, 5.78000000e+02,
       1.00000000e+00, 4.20000000e+01, 2.13000000e+02, 2.10000000e+01,
       3.80000000e+01, 6.72000000e+02, 1.16700000e+03, 1.61000000e+02,
       1.00000000e+01, 2.25000000e+02, 8.10000000e+01, 3.40000000e+02,
       9.58000000e+02, 3.79000000e+02, 3.90000000e+01, 3.30000000e+01,
       3.80000000e+01, 1.12000000e+02, 1.10000000e+02, 1.98000000e+02,
       1.12000000e+02, 1.20000000e+01, 1.80000000e+02, 1.28000000e+02,
       1.35300000e+03, 2.30000000e+01, 1.14000000e+03, 9.49000000e+02,
       3.16000000e+02, 2.00000000e+00, 2.20000000e+02, 9.80000000e+01,
       1.60000000e+01, 6.87000000e+02, 1.03000000e+02, 5.33000000e+02,
       5.10000000e+01, 3.20000000e+01, 3.41000000e+02, 5.47000000e+02,
       8.70000000e+01, 8.40000000e+01, 1.34000000e+02, 2.06000000e+02,
       1.30000000e+02, 4.60000000e+01, 1.80000000e+01, 1.18000000e+02,
       6.49000000e+02, 3.37000000e+02, 5.80000000e+01, 1.64000000e+02,
       1.79000000e+02, 6.10000000e+01, 1.92000000e+02, 2.10000000e+01,
       1.58000000e+02, 1.81000000e+02, 3.41060513e-13, 4.02000000e+02,
       1.30000000e+01, 1.35000000e+02, 4.10000000e+02, 1.14000000e+02,
       1.39000000e+02, 1.01000000e+02, 1.90000000e+01, 8.52000000e+02,
       1.37000000e+02, 1.14000000e+02, 4.50000000e+01, 2.76000000e+02,
       1.50000000e+01, 9.00000000e+00, 3.20000000e+01, 1.08000000e+02,
       7.40000000e+01, 2.26000000e+02, 1.43600000e+03, 3.34000000e+02,
       3.41060513e-13, 1.04000000e+03, 1.35300000e+03, 7.70000000e+01,
       8.06000000e+02, 2.00000000e+02, 1.39100000e+03, 4.71000000e+02,
       1.41971000e+05, 6.40000000e+01, 2.80700000e+03, 4.89000000e+02,
       3.41000000e+02, 8.00000000e+00, 6.80000000e+01, 2.30000000e+02,
       5.90000000e+01, 1.11000000e+02, 5.86000000e+02, 1.00000000e+00,
       3.25000000e+02, 3.97000000e+02, 2.08000000e+02, 5.40000000e+01,
       3.90000000e+01, 5.93000000e+02, 4.34000000e+02, 3.11000000e+02,
       3.17000000e+02, 3.46000000e+02, 1.00000000e+01, 2.43000000e+02,
       6.30000000e+02, 1.99000000e+02, 1.30000000e+01, 1.90000000e+01,
       7.30000000e+01, 4.10000000e+01, 2.48000000e+02, 1.47000000e+02,
       1.72000000e+02, 1.11000000e+02, 9.90000000e+01, 1.90000000e+01,
       1.20000000e+01, 1.06000000e+02, 4.83000000e+02, 2.20000000e+01,
       3.41060513e-13, 5.72000000e+02, 3.10000000e+01, 2.84000000e+02,
       8.00000000e+00, 1.90000000e+02, 7.87000000e+02, 1.33900000e+03,
       3.30000000e+01, 5.70000000e+01, 4.10000000e+01, 5.67000000e+02,
       3.00000000e+01, 1.59000000e+02, 4.20000000e+01, 9.22000000e+02,
       1.00510000e+04, 2.71000000e+02, 6.62000000e+02, 6.00000000e+01,
       8.29000000e+02, 8.80000000e+01, 7.10000000e+01, 1.55000000e+02,
       1.80000000e+01, 1.50000000e+02, 6.42000000e+02, 3.19000000e+02,
       1.84000000e+02, 2.80000000e+03, 9.70000000e+01, 3.41060513e-13,
       1.26000000e+02, 2.92000000e+02, 6.20000000e+01, 8.00000000e+01,
       4.10000000e+01, 1.50000000e+01, 3.70000000e+01, 3.41060513e-13,
       1.85000000e+02, 1.00000000e+01, 5.80000000e+01, 2.40000000e+01,
       1.86000000e+02, 1.02000000e+03, 1.18000000e+02, 1.14000000e+02,
       3.43000000e+02, 4.04000000e+02, 2.40000000e+01, 4.70000000e+01,
       1.07000000e+02, 6.00000000e+01, 6.47300000e+03, 1.10000000e+02,
       9.40000000e+01, 3.15000000e+02, 1.09900000e+03, 1.98500000e+03,
       6.60000000e+01, 3.50000000e+01, 8.30000000e+01, 3.41060513e-13,
       4.37000000e+02, 2.52800000e+03, 5.71000000e+02, 1.42000000e+02,
       7.67000000e+02, 6.80000000e+01, 7.80000000e+01, 5.80000000e+01,
       5.90000000e+01, 1.94000000e+02, 1.16500000e+03, 2.42000000e+02,
       9.20000000e+01, 5.40000000e+01, 4.69000000e+02, 2.50000000e+01,
       1.64000000e+02, 4.40000000e+01, 8.96000000e+02, 6.20000000e+01,
       1.23200000e+03, 3.60000000e+01, 7.70000000e+01, 5.41000000e+02,
       1.70000000e+01, 5.80000000e+01, 2.36800000e+03, 3.34000000e+02])

In [39]:
Y1_pred = regr_train.predict(X1)
Y1_pred

array([2.0190e+03, 2.6000e+01, 6.7400e+02, 4.4500e+02, 2.5000e+01,
       8.2000e+01, 3.7000e+02, 8.8000e+01, 2.6000e+01, 1.4710e+03,
       2.2670e+03, 8.4000e+01, 5.5000e+01, 6.6000e+01, 2.9800e+02,
       3.8000e+01, 1.8000e+01, 6.0100e+02, 5.1000e+01, 1.5000e+01,
       1.1000e+01, 2.0000e+00, 9.6500e+02, 6.7000e+01, 3.5100e+02,
       1.5870e+03, 5.0900e+02, 3.1500e+02, 3.4400e+02, 2.1000e+01,
       1.0800e+02, 7.9200e+03, 2.4800e+02, 3.7200e+02, 6.1300e+02,
       2.9000e+01, 6.0000e+00, 5.9000e+01, 2.9800e+02, 7.5000e+01,
       2.5570e+03, 4.5530e+03, 5.7500e+02, 2.1600e+03, 2.3000e+01,
       2.8000e+01, 2.4700e+02, 2.5000e+01, 3.2000e+01, 8.7000e+01,
       9.0700e+02, 5.6000e+01, 9.1700e+02, 4.0400e+02, 6.1500e+02,
       3.1000e+01, 7.0100e+02, 3.8800e+02, 1.0000e+00, 1.1000e+01,
       9.5500e+02, 4.8130e+03, 3.1600e+02, 5.7400e+02, 2.6800e+02,
       2.3100e+02, 6.0000e+01, 3.7900e+02, 6.0200e+02, 5.1000e+02,
       3.2000e+01, 8.3200e+02, 1.0080e+03, 8.0100e+02, 7.0000e+01,
       1.1200e+02, 2.7000e+01, 2.9633e+04, 2.9500e+02, 4.3000e+01,
       1.0670e+03, 4.8000e+01, 4.5000e+01, 6.7820e+03, 8.2000e+01,
       5.5400e+02, 3.0100e+02, 2.0700e+02, 3.1980e+03, 2.9000e+01,
       3.3700e+02, 3.5300e+02, 5.0100e+02, 1.3100e+02, 6.9200e+02,
       1.6260e+03, 1.7700e+02, 1.4500e+02, 5.0900e+02, 7.8300e+02,
       2.4000e+01, 1.0700e+02, 1.6700e+02, 2.7900e+02, 4.6100e+02,
       7.3300e+02, 1.6000e+01])

## This is a more elegent solution for converting df['Robbery'] to a series of binary values:

df['Robbery binary'] = df['Robbery'].apply(lambda x: 1 if x > 0 else 0)